# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
env:
  global:
    - ROS_DISTRO=melodic
    - ROS_REPO=ros

jobs:
  fast_finish: true
  include:
    - env: TEST="clang-format catkin_lint"
    - env: TEST=code-coverage
           DOCKER_IMAGE=moveit/moveit:master-source
    - env: DOCKER_IMAGE=moveit/moveit:master-source
  allow_failures:
    - env: TEST=code-coverage

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - .moveit_ci/travis.sh
