mqtt:
  client:
    protocol: 4      # MQTTv311
    client_id: client1
    clean_session: False
  connection:
    host: 192.168.1.100 #10.101.12.86
    port: 8883
    keepalive: 5
  private_path: device/001
# Default is json serialiser, msgpack is more efficient
serializer: msgpack:dumps
deserializer: msgpack:loads

# image to publish on server
bridge:
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: sensor_msgs.msg:CompressedImage
    topic_from: /camera/image_raw/compressed
    topic_to: /camera/image_raw/compressed
    latched: false
    qos: 2

  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: sensor_msgs.msg:CompressedImage
    topic_to: /detected/image_raw/compressed
    topic_from: /detected/image_raw/compressed
    latched: false
    qos: 2

