mqtt:
  client:
    protocol: 4      # MQTTv311
    client_id: client1
    clean_session: False
  connection:
    host: $(arg mqtt_bridge_ip)
    port: $(arg mqtt_bridge_port)
    keepalive: 5
  private_path: device/001
# Default is json serialiser, msgpack is more efficient
serializer: msgpack:dumps
deserializer: msgpack:loads

# image to publish on server
bridge:
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: sensor_msgs.msg:Image
    topic_from: /usb_cam/image_raw/compressed
    topic_to: /usb_cam/image_raw/compressed
    latched: false
    qos: 2

  # - factory: mqtt_bridge.bridge:MqttToRosBridge
  #   msg_type: fastpick_msgs.msg:StrawberryObjects
  #   topic_from: /detected_strawberries
  #   topic_to: /through_mqtt_bridge/detected_strawberries
  #   latched: false 
  #   qos: 2
